### ISSUE TITLE
Fail with RequireJS

### ISSUE THREAD

**Issue by Ajaxy** [niklasvh/html2canvas#533] opened 2015-02-11 18:12 UTC
`html2canvas` is not compatible with RequireJS modular system and it even fails with its non-AMD "shims" mechanism.

It happens because `html2canvas` contains vendor libraries such as `es6-promise` and `punycode` that provide themselves into AMD modular system making modular system think that the whole file is raw AMD module.

Please, add support for AMD, because now it's impossible to use it normally. Thanks.

**Comment by usmonster** [comment] 2015-02-12 22:25
Duplicate of #528--feel free to subscribe to that issue and close this one.

**Closed** 2015-02-13 09:50 UTC
