### ISSUE TITLE
Way to increase resolution of the image generated via toDataURL

### ISSUE THREAD

**Issue by tankchintan** [niklasvh/html2canvas#241] opened 2013-07-09 22:28 UTC
This is more of a feature request. I am easily able to generate the PNG by calling `toDataURL` on the returned `canvas`. But the quality of the image is rather blurry/poor. I did some googling & found out that by default it just returns an image at 96 dpi. And there doesnt seem to be a standard way of improving this. Also the `toDataURLHD` is experimental and does not work any ways.

Is there any way `html2canvas` can return an image at a higher resolution? Or even if it can provide a way to get the DOM being rendered, I can use some library that uses the DOM (with all the computed styles applied to it) and then generate whatever image I want.

**Comment by Ajaxy** [comment] 2015-01-29 00:30
@mudcube worked out partially for me

**Comment by syamvilakudy** [comment] 2015-02-12 05:32
@brcontainer its working fine for me

**Comment by mfkj** [comment] 2015-03-20 13:22
is there any solution found?? please share how to enhance resolution of blurry image i have to make a pdf of it

**Comment by jpatel3** [comment] 2015-04-23 20:54
+1 is there any solution/guide line for this yet?

**Comment by ejlocop** [comment] 2015-05-04 08:56
any solution found ?

**Comment by Ajaxy** [comment] 2015-05-04 16:31
Guys, use `transform: scale(2, 2)` it works out.

**Comment by matiasinsaurralde** [comment] 2015-05-14 11:25
Can you provide more details?

**Comment by Ajaxy** [comment] 2015-05-22 15:54
@matiasinsaurralde right before making screen shot add css class `.x2` containing css rule from above to the element, then remove that class in `html2canvas` callback. You will get double-sized element and double-sized screenshot also.

**Comment by ejlocop** [comment] 2015-06-16 11:04
![image](https://cloud.githubusercontent.com/assets/12082880/8181636/2630494c-145a-11e5-8903-36c299f6a4f9.png)
screenshot when i tried to follow ur  suggestion @Ajaxy . i think the problem is on my code? it took so long to render the page

**Comment by yonatanmn** [comment] 2015-11-12 16:22
scale did not increase resolution for me. Had to solve it with JS  - 
https://github.com/niklasvh/html2canvas/issues/379

**Comment by premreddyn** [comment] 2016-01-02 22:13
Any luck guys?

**Comment by mathiasleroy** [comment] 2016-01-15 11:06
`transform: scale(2, 2);` is not the solution for dygraph.js either

**Comment by yonatanmn** [comment] 2016-01-15 11:12
@premerddyn, see my solution in the linked issue.
It is working well, but requires enlargement before screenshot. 
If my comment isn't clear I'll add more explanation

**Comment by premreddyn** [comment] 2016-01-16 18:39
well what i had done is make a twice size div and made it visibility collapse and every content i had in here i posted to that div and took a screenshot.That way no image clarity is loss and i tweaked some font size code to make it work.I get this working fine.But my problem is with text-stroke and multiline text-background.

**Comment by ilanle** [comment] 2016-03-08 09:26
scaling by 2 works for me, however, I find that the rendering is limited by the window resolution/size. If the scaled div is wider than the window, then part of it will be cut off

**Comment by vance** [comment] 2016-04-30 20:34
so, is there no way to capture canvases larger than the screen?

**Comment by vance** [comment] 2016-04-30 20:47
Ah, from [this](https://github.com/niklasvh/html2canvas/issues/461) thread:  

```
var h = $(element)[0].ownerDocument.defaultView.innerHeight;
    $(element)[0].ownerDocument.defaultView.innerHeight = $(element).height();
    html2canvas($(element)).then(function(canvas) {
        $(element)[0].ownerDocument.defaultView.innerHeight = h;
        //Do whatever you want with your canvas
    }
```

**Comment by enjoytheday** [comment] 2016-05-07 13:22
https://jsfiddle.net/enjoythedaycsk/9L966sdd/1/

I tried to achieve high resolution thing in this example but didn't get that...

Click on download pngx2 button..

Is it possible to do operations on backend like when button is clicked canvas turns into twice its size and then pic is captured and then again canvas is taken back to regular size..

**Comment by vance** [comment] 2016-05-11 06:24
Sure, you could do that. I trigger a canvas of the size I want using the
code provided. I found that getting the value can be immaculate, so I just
set the width/height directly.

On Saturday, May 7, 2016, enjoytheday <notifications@github.com> wrote:

> https://jsfiddle.net/enjoythedaycsk/9L966sdd/1/
>
> I tried to achieve high resolution thing in this example but didn't get
> that...
>
> Click on download pngx2 button..
>
> Is it possible to do operations on backend like when button is clicked
> canvas turns into twice its size and then pic is captured and then again
> canvas is taken back to regular size..
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/niklasvh/html2canvas/issues/241#issuecomment-217634634>
>


-- 


The World's Longest Ongoing Illustration
ForeverScape.com <http://www.foreverscape.com/> | @foreverscape
<https://twitter.com/foreverscape>  | On Github
<https://github.com/vance/foreverscapecore> | In the News
<http://www.foreverscape.com/art/reviews/>

**Comment by enjoytheday** [comment] 2016-05-16 10:51
@vance can you please set this this in jsfiddle example?

https://jsfiddle.net/enjoythedaycsk/9L966sdd/1/

I tried but its not being set by me.

You can edit it completely or can create new one.

It will be helpful to many :dancer:

**Comment by jpatel3** [comment] 2016-05-16 17:39
@enjoytheday download pngx2 doesn't download the full image
![image 3](https://cloud.githubusercontent.com/assets/1363884/15298076/8c7f1a5c-1b6b-11e6-8480-36dc7896014c.png)
![image 4](https://cloud.githubusercontent.com/assets/1363884/15298075/8c7f2c04-1b6b-11e6-9a78-7d877b47a139.png)

**Comment by vance** [comment] 2016-05-19 18:11
I tried to mock it up quickly but didn't have time to fix the test div. Capturing something with `transform:scale()` doesn't do anything because the internal height of the div is _NOT_ affected. That's why it's a transform. It's w/h properties are unchanged (internally), which you can test by getting `getBoundingClientRect()`.  It's width/height only _actually_ change when viewed in the context of the parent. You have to grab the container div after it's scaled.

**Comment by AndyBoat** [comment] 2016-09-05 09:48
I face a same problem, is there any workable solution?ヾ(´･ ･｀｡)ノ"

**Comment by vance** [comment] 2016-09-05 18:49
I was able to get it to work, to capture elements larger than the window. Just rememveb, you can't get a "larger" image simply from a transformed element, because (to itself), it still has the same dimensions. 

**I had to do mine in an iframe and send the base64 data back as a message...because doing the following BREAKS the window resize event.**

Again with comments:
```
   //store the original height
    var h = $(element)[0].ownerDocument.defaultView.innerHeight;
    //set it to the documents
    $(element)[0].ownerDocument.defaultView.innerHeight = $(element).height();
    //again for height
    var w = $(element)[0].ownerDocument.defaultView.innerWidth;
    //set it to the documents
    $(element)[0].ownerDocument.defaultView.innerWidth = $(element).width();

    html2canvas($(element)).then(function(canvas) {
//restore the document size
        $(element)[0].ownerDocument.defaultView.innerHeight = h;
        $(element)[0].ownerDocument.defaultView.innerWidth = w;
        //Do whatever you want with your canvas
    }
```

**Comment by airdrummingfool** [comment] 2016-09-14 19:22
I wrote the following function to easily get a higher-DPI screenshot from an HTML element using html2canvas.
* if the height or width is constrained (e.g. there is a fixed body width), the constraints must be removed during processing - the source element must be able to grow up to the desired scale
* `srcEl` should be an existing element
* `destIMG` should be an existing (empty) image element
* `dpi` should be multiples of 96

```js
var makeHighResScreenshot = function(srcEl, destIMG, dpi) {
	var scaleFactor = Math.floor(dpi / 96);
	// Save original size of element
	var originalWidth = srcEl.offsetWidth;
	var originalHeight = srcEl.offsetHeight;
	// Save original document size
	var originalBodyWidth = document.body.offsetWidth;
	var originalBodyHeight = document.body.offsetHeight;

	// Add style: transform: scale() to srcEl
	srcEl.style.transform = "scale(" + scaleFactor + ", " + scaleFactor + ")";
	srcEl.style.transformOrigin = "left top";

	// create wrapper for srcEl to add hardcoded height/width
	var srcElWrapper = document.createElement('div');
	srcElWrapper.id = srcEl.id + '-wrapper';
	srcElWrapper.style.height = originalHeight*scaleFactor + 'px';
	srcElWrapper.style.width = originalWidth*scaleFactor + 'px';
	// insert wrapper before srcEl in the DOM tree
	srcEl.parentNode.insertBefore(srcElWrapper, srcEl);
	// move srcEl into wrapper
	srcElWrapper.appendChild(srcEl);

	// Temporarily remove height/width constraints as necessary
	document.body.style.width = originalBodyWidth*scaleFactor +"px";
	document.body.style.height = originalBodyHeight*scaleFactor +"px";

	window.scrollTo(0, 0); // html2canvas breaks when we're not at the top of the doc, see html2canvas#820
	html2canvas(srcElWrapper, {
		onrendered: function(canvas) {
			destIMG.src = canvas.toDataURL("image/png");
			srcElWrapper.style.display = "none";
			// Reset height/width constraints
			document.body.style.width = originalBodyWidth + "px";
			document.body.style.height = originalBodyHeight + "px";
		}
	});
};
```

Usage:
```js
var src = document.getElementById("screenshot-source");
var img = document.getElementById("screenshot-img");
makeHighResScreenshot(src, img, 192); // DPI of 192 is 4x resolution (2x normal DPI for both width and height)
```

**Comment by vance** [comment] 2016-09-14 19:32
Did you find that doing this also breaks window.onresize event handlers? For this reason, I had to do all of this inside an iframe and post the result back using parent.window.postMessage(data) to return the contents. This only matters to me because it is a mobile App, and it is critical to have onresize fire.

**Comment by airdrummingfool** [comment] 2016-09-14 20:03
@vance: In my case I don't need or use any of those things - I'm actually using this to work around a bug in an HTML-to-PDF renderer. I'd love to see a full example of your method, it seems more flexible.

**Comment by airdrummingfool** [comment] 2016-09-16 20:49
I figured out another way to get a high resolution image that doesn't need to resize the body. However, it does have to do some other crazy stuff because of a bug in html2canvas (#790, #820, #893, #922, etc), which means it may not work for everyone. Based on @MisterLamb's [retina code](https://github.com/niklasvh/html2canvas/issues/390#issuecomment-208068027).

```js
function takeHighResScreenshot(srcEl, destIMG, scaleFactor) {
	// Save original size of element
	var originalWidth = srcEl.offsetWidth;
	var originalHeight = srcEl.offsetHeight;
	// Force px size (no %, EMs, etc)
	srcEl.style.width = originalWidth + "px";
	srcEl.style.height = originalHeight + "px";

	// Move the element to the top of the page because of a bug in html2canvas
	// that, when supplying a custom canvas, offsets the rendering on the custom
	// canvas based on the offset of the source element on the page; thus the
	// source element MUST be at 0, 0 of the page
	// This means that if the body has a margin, it must be removed also
	// See html2canvas issues #790, #820, #893, #922
	document.body.insertBefore(srcEl, document.body.firstChild);
	// Remove source margin
	srcEl.style.margin = "0";
	// Save and remove body margin
	var originalBodyMargin = document.body.style.margin;
	document.body.style.margin = "0";

	// Create scaled canvas
	var scaledCanvas = document.createElement("canvas");
	scaledCanvas.width = originalWidth * scaleFactor;
	scaledCanvas.height = originalHeight * scaleFactor;
	scaledCanvas.style.width = originalWidth + "px";
	scaledCanvas.style.height = originalHeight + "px";
	var scaledContext = scaledCanvas.getContext("2d");
	scaledContext.scale(scaleFactor, scaleFactor);

	html2canvas(srcEl, { canvas: scaledCanvas })
	.then(function(canvas) {
		destIMG.src = canvas.toDataURL("image/png");
		srcEl.style.display = "none";
		scaledCanvas.style.display = "none";
		document.body.style.margin = originalBodyMargin;
	});
};
```

Usage:
```js
var src = document.getElementById("screenshot-src");
var img = document.getElementById("screenshot-img");
takeHighResScreenshot(src, img, 2); // This time we provide desired scale factor directly, no more messing with DPI
```

**Comment by vance** [comment] 2016-09-20 03:24
@airdrummingfool that works for elements smaller than window, but I get invalid data for src elements larger than window. Scaling it down with `transform:scale()` does not work, either. It's like the src buffer is too large. That is, the GPU doesn't bother rendering things outside the window. In this case, changes to the src HTML are required (like scaling of images and changing positions).

**Comment by Nomia** [comment] 2016-10-31 13:09
this works with the newest version(0.5.0-alpha). but not 0.4.1

if you wanna solve this issue in 0.4.1, you have to play around with the canvas size.

**Comment by tregenza** [comment] 2016-11-06 18:34
Just a quick note for anyone using @airdrummingfool 's fix (which works great)...

You cannot have any "relative" elements wrapping the element you wish to screen dump no matter how far up the xtree they are. They need to be switched to static for the duration of screendump so the element you want actually appears at 0,0 relative to the window, not a surrounding DIV. 

It took me several hours to work this out so I hope this helps someone avoid the same problems.

**Comment by Jacksta66** [comment] 2017-02-10 04:33
Good Afternoon guys,
does anybody have a jsfiddle of @airdrummingfool solution, I am trying to implement it in my project with no luck. A working example would be great for me to understand how this works and would help me very much in trying to implement it in my project.

Thankyou very much for any assistance that can be provided.

**Comment by mora260** [comment] 2017-05-25 04:10
Hi everyone! I'm trying to use @airdrummingfool solution. But I get one annoying error. Inside the element I want to get the image from, there is a <img> element and when doing the procedure, the img element goes blank and the src is ignored. Do you know how can I solve this? Has anyone face this issue before with html2canvas?

Thanks in advance to this thread! It's saving me!! :D

**Comment by mora260** [comment] 2017-05-25 05:09
Fixed the image problem!! The useCORS wasn't enabled! But I'm still getting only half the image rendered.

**Comment by eKoopmans** [comment] 2017-05-25 05:22
Great! The half-image might be due to the [off-canvas rendering issue](https://github.com/niklasvh/html2canvas/pull/1083). I've also made a pull request to [add resolution/scaling to html2canvas](https://github.com/niklasvh/html2canvas/pull/1087), you may find it easier to use than the @airdrummingfool solution.

Until those get merged in to html2canvas, you can get my custom build with both of those and a few other bugfixes [here](https://github.com/eKoopmans/html2canvas/tree/develop/dist).

**Comment by mora260** [comment] 2017-05-25 05:30
Hi @eKoopmans. Thanks for your answer. I just managed to fix mine by multiplying the height by 2. But, I think I'm getting a bigger image with white spaces above and below... so... I'm gonna try yours and report back in a few minutes!

**Comment by mora260** [comment] 2017-05-25 05:40
OM(F)G @eKoopmans .. Yours worked out of the box. Thanks a lot man. That pull request... they should just accept it now. There are A LOT of people wanting this dpi option for html2canvas.

**Comment by niklasvh** [comment] 2017-07-27 07:26
Closing in favor of #1087

**Closed by niklasvh** 2017-07-27 07:26 UTC

**Comment by venuvadde** [comment] 2018-04-19 08:28
@airdrummingfool ... Thank you. That works perfect.

**Comment by shakercs** [comment] 2019-06-01 09:12
you can use https://github.com/cburgmer/rasterizeHTML.js

**Comment by michelvambattu** [comment] 2019-06-13 12:19
> Have you tried using CSS transform matrix on a parentNode to the element you're wishing to export at a higher resolution? This works for me. E.g. "transform: scale(2, 2)"

Could you please eloborate on this?

**Comment by snowPu** [comment] 2019-08-16 07:33
latest version of html2canvas provides you with an option of scaling. Works really well.

html2canvas(element, {
    scale: 2
});

**Comment by jsrpy** [comment] 2019-09-23 02:51
For multiple page pdf rendering from html and image content, setting `scale: 1` might fix the resolution issue and at the same time avoid images exceeding the pdf border.

**Comment by aljeesjose** [comment] 2020-02-24 07:06
I think this helps, i used html2canvas

downloadpdf() {
var doc = new jsPDF({
format: "a4"
});

  html2canvas(document.getElementById("pdf-doc"), {
    scale: "5"
  }).then(canvas => {
    this.imgFile = canvas;
    doc.addImage(this.imgFile, "JPEG", 5, 5, 200, 285);
    doc.save("filename" + ".pdf");
  });
}
