### ISSUE TITLE
 IndexSizeError in html2canvas 0.4.1 

### ISSUE THREAD

**Issue by sathiyendren** [niklasvh/html2canvas#625] opened 2015-07-02 12:16 UTC
I am getting  IndexSizeError while trying to get canvas of div which is having child. for more information I have attached screenshot below. Please find the attachment.

This issue is happening in windows 8.1 apps only. So this can be fixed by adding try catch to the  function renderItem(ctx, item) .

![image](https://cloud.githubusercontent.com/assets/2248479/8476728/935003f8-20e1-11e5-95ce-876a9312e277.png)

**Comment by brcontainer** [comment] 2015-07-03 17:36
Duplicate of https://github.com/niklasvh/html2canvas/issues/331 and https://github.com/niklasvh/html2canvas/issues/183

**Closed** 2017-12-11 10:32 UTC
