### ISSUE TITLE
Multiple unhandled/uncaught promise errors in console

### ISSUE THREAD

**Issue by mlev** [niklasvh/html2canvas#1502] opened 2018-04-12 01:47 UTC
### Bug reports:

Latest version produces multiple unhandled errors in the console - even though canvas appear to render correctly.

This can be reproduced on the demo site (https://html2canvas.hertzen.com/).

Tested on Chrome and Safari - both with the same result.
<img width="1402" alt="screen shot 2018-04-12 at 11 39 14 am" src="https://user-images.githubusercontent.com/3466386/38651919-01dd8b80-3e47-11e8-8ff3-9fa67cb0edce.png">
<img width="1205" alt="screen shot 2018-04-12 at 11 46 12 am" src="https://user-images.githubusercontent.com/3466386/38651949-2975e728-3e47-11e8-98a2-4641cfc59497.png">

### Specifications:

 * html2canvas version tested with:
 * Browser & version: Chrome 65, Safari 11.1
 * Operating system: Mac High Sierra

**Comment by tarjeieo** [comment] 2018-04-16 11:48
I see the same in both Chrome and Internet Explorer, on a Windows 10 PC.

**Comment by earshinov** [comment] 2019-02-22 18:38
We experience this, too, which is very annoying, particularly because we have [Sentry](https://sentry.io/) enabled and each unhandled promise rejection results in an error notification.

For us, the issue seems to be caused by hidden (zero-sized) frames present on the page. In html2canvas, rendering these frames results in `canvas.toDataUrl()` returning `data:,` (see [StackOverflow question](https://stackoverflow.com/questions/46017271/canvas-todataurl-returns-empty-data-string-using-array-and-loop)). When put into `ImageElement.src`, such data URL causes an `onerror` event, which html2canvas ties to the `reject` Promise callback here: https://github.com/niklasvh/html2canvas/blob/41eb8ab22fe9906824a9f03976c91f27a384bf72/src/Clone.js#L216

I have prepared a demo page. Unfortunately, due to browser's same-origin policy and additional restrictions set up on JSFiddle, you have to store this page somewhere and have it served by a web server (`python -m http.server` will suffice):

index.html:
```
<!DOCTYPE html>
<script src="http://unpkg.com/html2canvas@1.0.0-alpha.12/dist/html2canvas.js"></script>
<iframe src="/" style="display: none;" width="0" height="0"></iframe>
<button onclick="run()">Call html2canvas</button>
<script src="script.js"></script>
```

script.js:
```
(function() {
  function setup() {
    window.addEventListener('unhandledrejection', event => {
    	alert('Unhandled rejection');
    	console.error('Unhandled Promise rejection', event);
    }, false);

    const _Promise = window.Promise;
    const Promise = function(_cb) {
      if (new.target) {
        return new _Promise(function(resolve, _reject) {
          function reject(value) {
            debugger;
            console.error("Rejecting a Promise with value", value);
            return _reject(value);
          };
          return _cb(resolve, reject);
        });
      }
      return _Promise.apply(this, arguments);
    }
    // copy members
    for (const prop of Object.getOwnPropertyNames(_Promise))
      Object.defineProperty(Promise, prop, Object.getOwnPropertyDescriptor(_Promise, prop));
    window.Promise = Promise;
  }

  function run() {
  	html2canvas(document.body, {
      width: window.innerWidth,
    	height: window.innerHeight,
      windowWidth: window.innerWidth,
      windowHeight: window.innerHeight,
    }).then(canvas => {
    	const img = document.createElement('img');
      img.src = canvas.toDataURL();
      document.body.appendChild(img);
    });
  }

  setup();

  window.run = run;
})();
```

![image](https://user-images.githubusercontent.com/52021/53262651-4043ab80-36e8-11e9-8671-5ec23ceb0266.png)

To me, ignoring `onerror` in case of an empty data URL seems to be a feasible solution:

Clone.js:
```
//iframeCanvas.onerror = reject;
iframeCanvas.onerror = function (event) {
    // Empty iframes may result in empty "data:," URLs, which are invalid from the <img>'s point of view
    // and instead of `onload` cause `onerror` and unhandled rejection warnings
    iframeCanvas.src == 'data:,' ? resolve(canvas) : reject(event);
};
```

**Comment by niklasvh** [comment] 2019-04-07 06:53
Fixed in https://github.com/niklasvh/html2canvas/pull/1762

**Closed by niklasvh** 2019-04-07 06:53 UTC
