### ISSUE TITLE
Google Maps API V3

### ISSUE THREAD

**Issue by iliauk** [niklasvh/html2canvas#584] opened 2015-04-30 09:37 UTC
Hi I have been trying to use this to capture screenshots of a few custom maps I have created in GMaps however I have some trouble capturing the whole map.

If I just set:

useCORS:true 

Then I only get the base map and not any of the markers/polygons/etc. 

I also tried using a proxy (perhaps incorrectly?) however that produces a worse result (as I don't even get the background map).

My full code is this:

<script type="text/javascript" src="./html2canvas.js"></script>

html2canvas($('#map'), {
    //html2canvas(document.getElementById('map'), {
        useCORS: true,
       // proxy: './html2canvasproxy.php',
        logging : true,
        onrendered: function(canvas) {
                    var myImage = canvas.toDataURL("image/png");
                    window.open(myImage);
        }
    }); 
}

I am running this locally if that causes any issue with the proxy?

My log is this:

html2canvas.js:2506 3899ms html2canvas: Succesfully loaded image #35 
ImageContainer {src: "http://mt1.googleapis.com/vt?pb=!1m4!1m3!1i6!2i31!…3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0", image: img, tainted: null, promise: $$es6$promise$promise$$Promise}
4
Coral_200 - test.html:1 Image from origin 'http://google-maps-utility-library-v3.googlecode.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
html2canvas.js:2506 4393ms html2canvas: Succesfully loaded image #34 
ImageContainer {src: "http://mt1.googleapis.com/vt?pb=!1m4!1m3!1i6!2i31!…3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0", image: img, tainted: null, promise: $$es6$promise$promise$$Promise}
html2canvas.js:2506 4394ms html2canvas: Succesfully loaded image #33 
ImageContainer {src: "http://mt0.googleapis.com/vt?pb=!1m4!1m3!1i6!2i32!…3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0", image: img, tainted: null, promise: $$es6$promise$promise$$Promise}
html2canvas.js:2506 4395ms html2canvas: Succesfully loaded image #32 
ImageContainer {src: "http://mt0.googleapis.com/vt?pb=!1m4!1m3!1i6!2i32!…3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0", image: img, tainted: null, promise: $$es6$promise$promise$$Promise}
html2canvas.js:2506 4395ms html2canvas: Succesfully loaded image #31 
ImageContainer {src: "http://mt1.googleapis.com/vt?pb=!1m4!1m3!1i6!2i33!…3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0", image: img, tainted: null, promise: $$es6$promise$promise$$Promise}
html2canvas.js:2506 4397ms html2canvas: Succesfully loaded image #30 
ImageContainer {src: "http://mt0.googleapis.com/vt?pb=!1m4!1m3!1i6!2i30!…3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0", image: img, tainted: null, promise: $$es6$promise$promise$$Promise}
html2canvas.js:2506 4398ms html2canvas: Succesfully loaded image #29 
ImageContainer {src: "http://mt0.googleapis.com/vt?pb=!1m4!1m3!1i6!2i30!…3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0", image: img, tainted: null, promise: $$es6$promise$promise$$Promise}
html2canvas.js:2506 4399ms html2canvas: Succesfully loaded image #27 
ImageContainer {src: "http://mt1.googleapis.com/vt?pb=!1m4!1m3!1i6!2i33!…3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0", image: img, tainted: null, promise: $$es6$promise$promise$$Promise}
.

**Comment by usmonster** [comment] 2015-05-14 11:12
Duplicate of #244--feel free to subscribe to that issue and close this one.

**Closed** 2017-12-12 09:10 UTC
Labels: Needs More Information
