### ISSUE TITLE
How I stop console logging when foreign object redendering is true

### ISSUE THREAD

**Issue by FineStrokes** [niklasvh/html2canvas#1963] opened 2019-08-06 11:21 UTC
How I stop console logging when foreign object redendering is true
I have set logging as false and foreign object redendering as true in config 
But It logs messages in console related to foreign object rendering.
How do I prevent it

### Specifications:

 * html2canvas version tested with: "^1.0.0-rc.3",
 * Browser & version: All
 * Operating system:MacOS

**Comment by hakimio** [comment] 2019-08-09 10:40
This is duplicate of issue #1874.

**Comment by subramanya4shenoy** [comment] 2019-08-10 08:41
@FineStrokes  Okay, I would suggest you to take this JS and use it as a script in your angular project. then u will be able to edit it and comment the console. fixed for me.

**Closed** 2019-09-25 10:38 UTC
