### ISSUE TITLE
No support for Retina displays! Doesn't take a snapshot of current scroll position!

### ISSUE THREAD

**Issue by nodkrot** [niklasvh/html2canvas#384] opened 2014-05-12 23:08 UTC
Looks blurry on retina display. When scrolled on the page and trying to take a snapshot, the snapshot is still the top of the website.

**Comment by usmonster** [comment] 2015-01-15 14:41
Duplicate of #390, #57, #254.

**Closed** 2017-12-11 10:25 UTC
