### ISSUE TITLE
word-wrap:break-word is not working

### ISSUE THREAD

**Issue by hanc1208** [niklasvh/html2canvas#664] opened 2015-08-25 01:11 UTC
word-wrap:break-word is not working when the text is too long without any white spaces.

like &lt;div style="width:30px;height:100px;word-wrap:break-word;"&gt;aaaaaaaaaaaaaaa&lt;/div&gt;

**Comment by programmin1** [comment] 2015-08-25 03:28
Are you really using word-wrap:break-work? That is really bad when it turns parrot into par rot or worship into wors hip for example. I have yet to find a usable use for it but it is tempting when there is no such thing as max-font or force down to size in css.

**Comment by hanc1208** [comment] 2015-09-12 00:51
I know but this function is very necessary for my service.

The view of the user is
aaa
aaa
aaa
But the captured picture is
aaaaaaaaaaaaaaaaaaa

It is very ambigous for users.

**Comment by snarkitect** [comment] 2015-09-24 18:32
We're also having this problem.  We're using an html/text editor which uses break-word when a word is longer than the available width and has to be broken automatically.  The rendering we see after using html2canvas with letterRendering enabled does not match.  Often times, the line of text is rendered one line further down than it should without any wrapping at all.

**Comment by sureshotday** [comment] 2015-09-29 10:04
we are also facing the same issue.

**Comment by savokiss** [comment] 2015-11-11 10:11
I‘ve found a solution here: http://stackoverflow.com/questions/22317823/html2canvas-remove-multiple-spaces-and-line-break
It use `<div contenteditable="true"></div>` to replace `textarea`.

But I use angular and I must find out the `ng-model` issue.

**Comment by hanc1208** [comment] 2015-11-13 03:43
@savokiss can you create pull request that does auto-replacing if the option is specified?

**Comment by savokiss** [comment] 2015-11-13 04:24
I might replied the wrong issue, here is my solution #83 
@hanc1208 My solution is for the issue above and it don't need to edit the source code of this repo.

**Comment by flftfqwxf** [comment] 2015-11-23 07:14
I have same question

**Comment by mariusbike1983** [comment] 2015-12-18 09:56
Any news about this issue?

**Comment by mariusbike1983** [comment] 2015-12-27 19:07
I wanted to really test this issue and indeed it seems to be reproduced even with the test-console on the official page. I created a very simple webpage, located at http://mariusbike83.wix.com/test1. This page contains only some fields and a text-area with a very long string (without spaces to break it up). When this is rendered with html2canvas library, you'll notice that the string is one-lined.

Has anyone found a solution to this problem?

**Comment by codefactor** [comment] 2015-12-27 20:59
For my application, I downgraded from 0.5.0-alpha1 to v0.4.1 and it seemed to work, so I am just going to use that version. I haven't thoroughly tested, but for sure long strings of characters wrapped properly. Try this to see if it resolves the issue; although other bugs might be introduced in the process due to big differences in the versions.

**Comment by okitty** [comment] 2016-08-26 19:20
how about manually break texts with <span></span> ?

   <div id="words">aaaaaaaaaaaaaaaaaaa</div>     
  <script>
	 var tarr=$("#words").html().split("");
	 var tstr="";
	 tarr.map(function(v){
	 tstr=tstr+"<span>"+v+"</span>";	 
	 })
        $("#words").html(tstr);
 </script>

**Comment by wayrex** [comment] 2016-11-02 18:13
letterRendering set to true worked for me....
html2canvas options docs: https://html2canvas.hertzen.com/documentation.html

**Comment by SatoshiKawabata** [comment] 2017-06-08 01:40
Is there no way to resolve this problem without using `v0.4.1`...?

**Comment by eKoopmans** [comment] 2017-06-08 15:40
Hi @SatoshiKawabata, did you try using the option `letterRendering: true` suggested by @wayrex?

**Comment by SatoshiKawabata** [comment] 2017-06-09 00:21
@eKoopmans I tried that but it didn't work too.

**Comment by gelinger777** [comment] 2017-06-13 06:21
@eKoopmans  @SatoshiKawabata  I can confirm that on beta te letterRendering does not work too. Seems on older 0.4.1 version it works but on beta no.

**Comment by SatoshiKawabata** [comment] 2017-06-13 09:47
@gelinger777 I want to use this by `npm` so I added an issue #1143. I should wait.

**Comment by love-everyday** [comment] 2017-09-12 09:08
I had solved it.

change
```
var textList = (!this.options.letterRendering || noLetterSpacing(container)) && !hasUnicode(container.node.data) ? getWords(characters) : characters.map(function(character) {
   return punycode.ucs2.encode([character]);
});
```
to
```
var textList = characters.map(function(character) {
  return punycode.ucs2.encode([character]);
});
```

**Comment by thriveplanMaster** [comment] 2017-09-12 19:36
@love-everyday you should make a PR

**Comment by CodyMoore240** [comment] 2017-09-12 19:38
@love-everyday you should make a PR

**Comment by love-everyday** [comment] 2017-09-13 03:33
@CodyMoore240 It was already resolved in **1.0.0-alpha.1**

**Comment by CodyMoore240** [comment] 2017-09-13 13:11
Thank you i will fork.

**Closed** 2017-12-31 11:14 UTC
Labels: Feature

**Comment by wangyupo** [comment] 2019-01-29 14:57
I fixed it by add <i></i> before the word need break

**Comment by wangyupo** [comment] 2019-01-29 14:58
I fixed it by add `<i></i>` before the word need break

**Comment by wangyupo** [comment] 2019-01-29 15:00
I fixed it by add `<i></i>` before the word need break, and it looks like
`<p class="punch-card-info-word">
        <i></i>statutestatutestatutestatutestatutestatutestatutestatutestatutestatutestatutestatute
 </p>`

**Comment by wangyupo** [comment] 2019-01-29 15:00
I fixed it by add `<i></i>` before the word need break, and it looks like

> <p class="punch-card-info-word">
>         <i></i>statutestatutestatutestatutestatutestatutestatutestatutestatutestatutestatutestatute
>  </p>

**Comment by wangyupo** [comment] 2019-01-29 15:01
I fixed it by add `<i></i>` before the word need break, and it looks like

```
<p class="punch-card-info-word">
         <i></i>statutestatutestatutestatutestatutestatutestatutestatutestatutestatutestatutestatute
</p>
```

**Comment by omeriko** [comment] 2020-05-30 19:36
This issue started 5 years ago... and counting: 
I'd like to share with the world that i've found a way to bypass this annoying bug, 
I took the text from a textarea input : 

` var txt = modal_dialog_text_area_input.value;
`
then i replaced each whitespace with the following markup, in order to preserve whitespaces. Which html2canvas fails to do, and why we find ourselves at 3:00 AM in the morning here, instead of in bed: 

`paragraphElement.innerHTML = txt.replace(/\s/g, '<span> </span>'); `

Now the paragraph looks good and the screenshot html2canvas takes is OK.

Another thing: the paragraph element must have the following css rules:
```
    word-break: break-word;
    white-space: normal;

```
Take care y'all

**Comment by xiaowuyaozqt** [comment] 2021-08-13 01:11
> I had solved it.
> 
> change
> 
> ```
> var textList = (!this.options.letterRendering || noLetterSpacing(container)) && !hasUnicode(container.node.data) ? getWords(characters) : characters.map(function(character) {
>    return punycode.ucs2.encode([character]);
> });
> ```
> 
> to
> 
> ```
> var textList = characters.map(function(character) {
>   return punycode.ucs2.encode([character]);
> });
> ```

'this.options.letterRendering' and 'noLetterSpacing(container)' work together,you can add CSS letter-spacing to solve it. if you use CSS word-break,you can  also change 
``` 
function noLetterSpacing(container) {
                return (/^(normal|none|0px)$/.test(container.parent.css("letterSpacing")));
}
```
to 
```
function noLetterSpacing(container) {
                return (/^(normal|none|0px)$/.test(container.parent.css("letterSpacing")))&&!(/^(break-word|break-all)$/.test(container.parent.css("wordBreak")));
}
```

**Comment by MostafaHamidian** [comment] 2026-01-05 15:07
html2canvas:
parent node set display: table;
child node set display: table-cell; vertical-align: middle | top | ...
