### ISSUE TITLE
Generated Canvas Cropped when page is scrolled

### ISSUE THREAD

**Issue by ScottEnock** [niklasvh/html2canvas#1981] opened 2019-08-24 10:00 UTC
### Bug reports:

Canvas created with HTML2Canvas is cropped if the window is not at the top of the page. The amount the image is cropped by is proportional to the distance scrolled from the top of the page. 

Correctly Renders:
![image](https://user-images.githubusercontent.com/27223098/63635736-fbc8a680-c65d-11e9-8eb6-d5d2c1a11ce8.png)

![image](https://user-images.githubusercontent.com/27223098/63635741-18fd7500-c65e-11e9-884e-050293c35539.png)

Render is cropped when scrolled:
![image](https://user-images.githubusercontent.com/27223098/63635758-42b69c00-c65e-11e9-9e0c-d10c4d4d52f8.png)

![image](https://user-images.githubusercontent.com/27223098/63635760-4e09c780-c65e-11e9-8ba8-e1dfc5553a33.png)

### Specifications:

 * html2canvas version tested with: npm v1.0.0-rc.3
 * Browser & version: Firefox 68.0.2 (64-bit)
 * Operating system: Windows 10

**Comment by hakimio** [comment] 2019-08-28 07:05
Duplicate of #1878

**Comment by ahmedfeyzi** [comment] 2020-12-05 12:33
> **I solved all possible problems as follows..**

```
html2canvas(element , {
        scrollX: -window.scrollX,
        scrollY: -window.scrollY,
        windowWidth: document.documentElement.offsetWidth,
        windowHeight: document.documentElement.offsetHeight
})
```

**Closed** 2021-08-04 12:58 UTC
