### ISSUE TITLE
Box-shadow and CSS transforms skew not supported? Fiddle provided

### ISSUE THREAD

**Issue by samsonkhisty** [niklasvh/html2canvas#510] opened 2015-01-19 23:44 UTC
Greetings, 
http://jsfiddle.net/fuggfuggfugg/q572g6q0/4/ - This is my working example. 
Tried searching but was unable to find anything with regards to skewed lines.

**Comment by samsonkhisty** [comment] 2015-01-19 23:49
updated: http://jsfiddle.net/fuggfuggfugg/q572g6q0/5/

**Comment by samsonkhisty** [comment] 2015-01-20 00:36
partly working code: http://codepen.io/fuggfuggfugg/pen/QwvvVq

**Comment by usmonster** [comment] 2015-01-20 15:33
Follow #221 for box shadow.

**Comment by samsonkhisty** [comment] 2015-01-23 14:59
Thanks. 
Another update, this code works for skew. http://codepen.io/fuggfuggfugg/pen/ZYyBRv
My first example used :before & :after which probably isn't supported.

**Comment by usmonster** [comment] 2015-01-23 15:15
@samsonkhisty What browser(s) are you testing in? IE, for example, apparently doesn't support pseudoelements in its implementation of `.getComputedStyle` until IE11... Though I see the same issue you're having on Chrome, so you're probably right that it's something not completely implemented in html2canvas..

**Comment by samsonkhisty** [comment] 2015-01-23 18:27
* My very first codepen (http://jsfiddle.net/fuggfuggfugg/q572g6q0/4/) does not work in any browser 
  * transform:skew specified in :before/:after is not applied 
  * Although gradients specified applied in the generated canvas 

* The latest codepen (http://codepen.io/fuggfuggfugg/pen/ZYyBRv) works perfectly in Chrome, Safari and FF. 
  * IE9: The HTML/CSS is perfect but canvas output on IE9 shows square boxes. 
  * I haven't had the opportunity to test in any latest IE or Opera yet.

**Comment by nyroDev** [comment] 2015-02-07 22:21
I'm also experiencing this issue with css transform.
I'm using a css similar to http://codepen.io/AtomicNoggin/pen/fEish

After digging a little in the code, I have the feeling that it has something to do with the clip definition of the rotated element, but not sure to get the whole.picture.
If the main dev could give me a hint on how to solve this problem, I could give it a try.

**Comment by usmonster** [comment] 2015-02-08 11:36
@samsonkhisty I just got a chance to check out your codepen example, and it looks fine in IE11 in both "Edge" and IE10 modes. IE9 mode throws some JS errors, though they seem to be coming from codepen itself, not html2canvas. According to [their documentation page](http://blog.codepen.io/documentation/), they only support IE10+. Can you try with jsFiddle or jsbin?

**Comment by niklasvh** [comment] 2017-12-12 09:00
Duplicate of #221

**Closed by niklasvh** 2017-12-12 09:00 UTC
