### ISSUE TITLE
border-radius bug

### ISSUE THREAD

**Issue by WebGuHui** [niklasvh/html2canvas#1351] opened 2018-01-02 09:46 UTC
version:
https://github.com/niklasvh/html2canvas/releases/download/v1.0.0-alpha.3/html2canvas.js

example:
http://jsfiddle.net/gyacgjgw/2/

![image](https://user-images.githubusercontent.com/11729740/34480014-dfa66308-efe4-11e7-8350-296586b5cdd5.png)

**Comment by niklasvh** [comment] 2018-01-08 13:46
Duplicate of https://github.com/niklasvh/html2canvas/pull/1084

**Closed by niklasvh** 2018-01-08 13:46 UTC
