### ISSUE TITLE
Text inside svg is converted twice

### ISSUE THREAD

**Issue by tksumanth1994** [niklasvh/html2canvas#734] opened 2015-11-18 14:59 UTC
In bar graph, the text 'Frequency' is appearing twice(in 2nd image). (1st image is html + div, 2nd image is canvas rendered by html2canvas)

![1](https://cloud.githubusercontent.com/assets/4353562/11244363/47057068-8e33-11e5-909e-6d75c192bba9.png)

**Comment by tksumanth1994** [comment] 2015-11-18 15:04
In bar graph, the text 'Frequency' is appearing twice(in 2nd image). (1st image is html + div, 2nd image is canvas rendered by html2canvas)

![1](https://cloud.githubusercontent.com/assets/4353562/11244363/47057068-8e33-11e5-909e-6d75c192bba9.png)

**Comment by brcontainer** [comment] 2015-11-18 20:08
Please put a example with jsfiddle.

**Comment by tksumanth1994** [comment] 2015-11-19 04:32
Here you go. @brcontainer 

http://jsfiddle.net/dgbwg4dy/1/

Notice how the normal text ("Graph Title") will render once but all the text inside the svg (text on the axis) will render twice. Some of them overlaps, so may be clear visibly. But you can see y-axis label on top-left clearly rendering twice because html2canvas is ignore the orientation of the text.

Note: This problem existed before this version ( in v0.4.1 - 7.9.2013). When I converted this using old html2canvas, the lines and bars inside svg were not rendering but the text was rendering. You can view that in this fiddle.

http://jsfiddle.net/dgbwg4dy/2/

Hope this helps.

**Comment by brcontainer** [comment] 2015-11-19 16:27
@tksumanth1994 It's really a bug, thank you for sharing the problem. html2canvas uses [fabric.js](https://github.com/kangax/fabric.js), then the problem is probably with the fabric.js

I think maybe you can create an open example only with frabric.js and open an issue at:

- https://github.com/kangax/fabric.js

**Comment by hyojin** [comment] 2015-11-20 07:13
Here is an another approach. 

https://github.com/hyojin/html2canvas/tree/fix%23541

**Comment by niklasvh** [comment] 2017-08-13 11:19
Fixed in https://github.com/niklasvh/html2canvas/tree/v1.0.0

**Closed by niklasvh** 2017-08-13 11:19 UTC
Labels: Unverified
