### ISSUE TITLE
Ability to only render what is on the screen

### ISSUE THREAD

**Issue by tobya** [niklasvh/html2canvas#542] opened 2015-02-19 08:48 UTC
Thanks for a great bit of code.

I have an odd use case.  I have a scrollable control (fullcalendar.io) and would like to be able to render it as it appears on the screen not scrolled to the top which seems to be the default behaviour.

This is how my page looks (please note my lack of css skills)

![screenhunter_07 19-feb-15 08 43](https://cloud.githubusercontent.com/assets/325502/6263710/63b9fb8a-b813-11e4-9232-cd51a3e1e49a.jpg)

and the is the html2canvas png I get when i call it on the containing Div.

![christopher_double](https://cloud.githubusercontent.com/assets/325502/6263722/818f8aee-b813-11e4-8380-821bc040466c.png)

As you can see the scrollable area has been scrolled up to the top, shifting the bits i'm interested in (the coloured blocks ) down.

Could someone point me to the area in the code where I could prevent this?

**Comment by usmonster** [comment] 2015-02-19 11:57
I think this is a duplicate of #511. Please check and, if you agree, feel free to follow that one and close this issue.

**Closed** 2015-02-19 14:06 UTC
