### ISSUE TITLE
placeholder color, font-size in <input> on Firefox , line wrap in <textarea>

### ISSUE THREAD

**Issue by Mapaler** [niklasvh/html2canvas#1894] opened 2019-06-18 10:18 UTC
#### Full picture
| Content | Real - Firefox | H2C - Firefox  | H2C - Chrome |
| --- | --- | --- | --- |
| Placeholder | ![Real With placeholder](https://user-images.githubusercontent.com/6565860/59669933-a8655280-91ed-11e9-914a-b415e75af9bf.png) | ![H2C in Firefox](https://user-images.githubusercontent.com/6565860/59669956-af8c6080-91ed-11e9-9c35-9bbf1e2b2b10.png) | ![H2C in Chrome](https://user-images.githubusercontent.com/6565860/59670382-70aada80-91ee-11e9-81fd-945500b84bf2.png) |
| String | ![Real With String](https://user-images.githubusercontent.com/6565860/59670085-e19dc280-91ed-11e9-9476-19708974d587.png) | ![H2C in Firefox](https://user-images.githubusercontent.com/6565860/59670104-ea8e9400-91ed-11e9-89d1-24fde2e25e38.png) | ![H2C in Chrome](https://user-images.githubusercontent.com/6565860/59670408-76082500-91ee-11e9-849a-d41874647448.png) |

#### Decomposing pictures
| Content | Real - Firefox | H2C - Firefox  | H2C - Chrome |
| --- | --- | --- | --- |
| `border-style: dashed;` | ![5](https://user-images.githubusercontent.com/6565860/59671152-c2a03000-91ef-11e9-87d0-54d65f6601dd.png) | ![6](https://user-images.githubusercontent.com/6565860/59671269-fa0edc80-91ef-11e9-92c6-ccfadc170388.png) | Same with Firefox |
| Placeholder `<Input>` | ![1](https://user-images.githubusercontent.com/6565860/59670785-12cac280-91ef-11e9-95b1-3233e6dd8c96.png) | ![2](https://user-images.githubusercontent.com/6565860/59670787-13635900-91ef-11e9-80c3-0b051ca38c73.png) | ![3](https://user-images.githubusercontent.com/6565860/59670789-13635900-91ef-11e9-9f0b-f56f2465af4d.png) |
| Placeholder `<textarea>` | ![4](https://user-images.githubusercontent.com/6565860/59670939-5c1b1200-91ef-11e9-8c94-f3d18060da76.png)  | Blank | Blank |
| String `<Input>` | ![4](https://user-images.githubusercontent.com/6565860/59671896-119a9500-91f1-11e9-895f-3bae421f9db4.png) | ![5](https://user-images.githubusercontent.com/6565860/59671897-119a9500-91f1-11e9-89ef-9e3249666f7d.png) | ![6](https://user-images.githubusercontent.com/6565860/59671898-119a9500-91f1-11e9-8641-baa3e2807e46.png) |
| String `<textarea>` | ![1](https://user-images.githubusercontent.com/6565860/59671623-92a55c80-91f0-11e9-9732-cdace3ae6522.png) | ![2](https://user-images.githubusercontent.com/6565860/59671638-976a1080-91f0-11e9-85f3-79b187727aec.png) | ![3](https://user-images.githubusercontent.com/6565860/59671642-9802a700-91f0-11e9-833a-ddfae73fd2aa.png) |

#### Detailed explanation
1. `border-style: dashed;` drawing error.

    | Real - Firefox | H2C - Firefox  | H2C - Chrome |
    | --- | --- | --- |
    | ![5](https://user-images.githubusercontent.com/6565860/59671152-c2a03000-91ef-11e9-87d0-54d65f6601dd.png) | ![6](https://user-images.githubusercontent.com/6565860/59671269-fa0edc80-91ef-11e9-92c6-ccfadc170388.png) | Same with Firefox |
1. `font-size` with `<input>` drawing error in Firefox.

    | Real - Firefox | H2C - Firefox  |
    | --- | --- |
    | ![1](https://user-images.githubusercontent.com/6565860/59670785-12cac280-91ef-11e9-95b1-3233e6dd8c96.png) | ![2](https://user-images.githubusercontent.com/6565860/59670787-13635900-91ef-11e9-80c3-0b051ca38c73.png) |
    | ![4](https://user-images.githubusercontent.com/6565860/59671896-119a9500-91f1-11e9-895f-3bae421f9db4.png) | ![5](https://user-images.githubusercontent.com/6565860/59671897-119a9500-91f1-11e9-89ef-9e3249666f7d.png) |
1. `color` with `<input>::placeholder` drawing error.

    | Real - Firefox | H2C - Firefox  | H2C - Chrome |
    | --- | --- | --- |
    | ![1](https://user-images.githubusercontent.com/6565860/59670785-12cac280-91ef-11e9-95b1-3233e6dd8c96.png) | ![2](https://user-images.githubusercontent.com/6565860/59670787-13635900-91ef-11e9-80c3-0b051ca38c73.png) | ![3](https://user-images.githubusercontent.com/6565860/59670789-13635900-91ef-11e9-9f0b-f56f2465af4d.png) |

    H2C uses string color, not placeholder color. If I modify the text color to red, the placeholder drawn by H2C  is also red.  
    ![2](https://user-images.githubusercontent.com/6565860/59673042-31cb5380-91f3-11e9-8082-42168b5e2adf.png)   
    ▼  
    ![1](https://user-images.githubusercontent.com/6565860/59672912-f6308980-91f2-11e9-94e5-dc848e1d18e2.png)
1.  Placeholder in `<textarea>` is not draw.

    | Real - Firefox | H2C - Firefox  | H2C - Chrome |
    | --- | --- | --- |
    | ![4](https://user-images.githubusercontent.com/6565860/59670939-5c1b1200-91ef-11e9-8c94-f3d18060da76.png)  | Blank | Blank |
1. Line wrap in `<textarea>` is not drawn.

    | Real - Firefox | H2C - Firefox  | H2C - Chrome |
    | --- | --- | --- |
    | ![1](https://user-images.githubusercontent.com/6565860/59671623-92a55c80-91f0-11e9-9732-cdace3ae6522.png) | ![2](https://user-images.githubusercontent.com/6565860/59671638-976a1080-91f0-11e9-85f3-79b187727aec.png) | ![3](https://user-images.githubusercontent.com/6565860/59671642-9802a700-91f0-11e9-833a-ddfae73fd2aa.png) |

#### Related pages
https://mapaler.github.io/PADDashFormation/

### Specifications:

 * html2canvas version tested with: [v1.0.0-rc.3](https://github.com/niklasvh/html2canvas/releases/tag/v1.0.0-rc.3)
 * Browser & version: Firefox Developer Edition 68.0b10 (64 bit) | Chrome 75.0.3770.90
 * Operating system: Microsoft Windows 10 1809 [Ver 10.0.17763.557]

**Comment by nidi3** [comment] 2020-03-19 00:53
Line wrap in textarea is a duplicate of #2008 ?

**Comment by Mapaler** [comment] 2020-03-19 03:51
Yes.

In order to solve this problem, I have now converted <input> content into <div> in my program, so I can solve it.

Thank you for your work.

Only the dotted line border I don't know how to do yet.

**Comment by MacrazdHao** [comment] 2021-08-05 03:21
How can u solve the problem of dotted line border at last?

**Comment by niklasvh** [comment] 2021-08-05 03:28
Dotted borders are now supported https://html2canvas.hertzen.com/results/border-dotted!Chrome_Stable-Chrome-92.0.4515.131.png

**Closed by niklasvh** 2021-08-05 03:28 UTC

**Comment by MacrazdHao** [comment] 2021-08-05 03:43
hello, I thought of a greate solution just now, you can use the div tag to draw a dashed or dotted line
    .dashed {
      width: 100%;
      overflow: hidden;
      margin-top: 10px;
      white-space: nowrap;
      line-height: 1px;
      height: 1px;
      font-size: 0;
      letter-spacing: 4px;
      .line {
        display: inline-block;
        width: 4px;
        height: 1px;
        background-color: #999999;
      }
    }
