### ISSUE TITLE
Angular build fails when using html2canvas with await/async

### ISSUE THREAD

**Issue by bampakoa** [niklasvh/html2canvas#1896] opened 2019-06-19 09:57 UTC
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)

### Bug reports:

When I run `ng build` to an Angular 7 application that uses `html2canvas` as:

`const canvas = await html2canvas(el as HTMLElement, { useCORS: true });`

I get the following error:

> error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("C:/my-app/node_modules/html2canvas/dist/types/index")' has no compatible call signatures.

### Specifications:

 * html2canvas version tested with: **1.0.0-rc.2 - 1.0.0-rc.7**
 * Browser & version:
 * Operating system: **Windows 10**

**Comment by hakimio** [comment] 2019-06-20 07:35
I am using RC1 and it works for me in Angular 7 app with async/await. Have you tried RC1? How are you importing html2canvas? Are you marking the function as "async"? Can you create a stackblitz example reproducing the issue?

**Comment by bampakoa** [comment] 2019-06-20 08:00
@hakimio as stated in the specifications of the issue above, the problem appears in RC2 and RC3.

**Comment by coolrb** [comment] 2019-06-23 17:40
Any solution to this problem? I just updated from Angular 6 to 7 and this problem started appearing

**Comment by hakimio** [comment] 2019-06-23 21:49
Use RC1?

**Comment by andorfermichael** [comment] 2019-06-25 13:27
Yes, it's definitely a problem regarding versions higher than 1.0.0-rc1. I have tested it with Angular 8 and can confirm that 1.0.0-rc.1 works, while 1.0.0-rc.2 and 1.0.0-rc.3 don't work.

**Comment by AdditionAddict** [comment] 2019-06-27 02:20
For those of us new to angular, if you're on Angular 8 this means changing package.json
```"html2canvas": "1.0.0-rc.1"```

**Comment by coolrb** [comment] 2019-06-27 06:39
@AdditionAddict 
RC1 helped me to build successfully. Thanks.

**Comment by CodeEpiphany** [comment] 2019-07-22 05:06
+1 for RC1 resolving my issue.

**Comment by jonnieZG** [comment] 2019-07-31 11:03
This is a serious issue that needs finxing, because:
1. The RC1 version does not support using tainted canvases (exporting pages with images that come from other sites)
2. The RC3 version can run in development mode after the second compilation attempt, but the project **can not be compiled for production** .

**Comment by hakimio** [comment] 2019-07-31 11:07
@jonnieZG 

1. Have you tried "useCORS" option with RC1? It should fix the image problem.
2. If it so important for you, why don't you open a PR?

**Comment by jonnieZG** [comment] 2019-08-01 05:56
> 1. Have you tried "useCORS" option with RC1? It should fix the image problem.
Yes, I did, and in RC1 and RC2 it does not work. Just in RC3.

> 2. If it is so important for you, why don't you open a PR?
??? What is this then?

**Comment by hakimio** [comment] 2019-08-01 06:35
> Yes, I did, and in RC1 and RC2 it does not work. Just in RC3.

That's strange, because for me with just useCORS set to true RC1 loads all the external images correctly. Maybe your 3rd party website has restrictive CORS policy?
Here is an example showing that it works as intended:
http://jsfiddle.net/jf7k82hq/

> > 1. If it is so important for you, why don't you open a PR?
> 
> ??? What is this #1896 then?

That's an issue not a pull request.

**Comment by jonnieZG** [comment] 2019-08-01 06:48
> That's strange, because for me with just useCORS set to true RC1 loads all the external images correctly. Maybe your 3rd party website has restrictive CORS policy?

Nah, I've set the cors headers returned by the host properly. It's a whole lotta other things in the game. However, on RC3 it works fine, on RC1 it does not. Since this is a tertiary issue in my project and I have a lot of bigger fish to fry, I'll let it simmer for a while until someone fixes it.

> > > 1. If it is so important for you, why don't you open a PR?
> > 
> > 
> > ??? What is this #1896 then?
> 
> That's an issue not a pull request.

Sorry, I was thinking of a "Problem Report". :) For a pull request I'd need to fix the issue and then ask the master to pull it to the main project. As I said, I can't engage in fixing also this library right now. I hope that the good people who maintain it would fix it eventually.

**Comment by manoranjan1999** [comment] 2020-04-21 12:33
> For those of us new to angular, if you're on Angular 8 this means changing package.json
> `"html2canvas": "1.0.0-rc.1"` and then running `npm i --verbose`

Thats really  work's for those who are using angular 8. Thanks

**Comment by andy1547** [comment] 2022-03-23 07:35
I'm getting this error in a TypeScript Webpack v5 project (no framework), used version1.0.0-rc.1 as a workaround.
This should be fixed so we can upgrade to the latest package.

**Closed** 2024-04-22 18:11 UTC
