### ISSUE TITLE
DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed

### ISSUE THREAD

**Issue by coder-shahezad** [niklasvh/html2canvas#2325] opened 2020-08-12 10:06 UTC
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.5
 * Browser & version: Android Device Web View
 * Operating system: Android

**Comment by claviska** [comment] 2020-12-09 15:45
Looks like a duplicate of https://github.com/niklasvh/html2canvas/issues/2058

**Closed** 2021-12-31 17:57 UTC
