### ISSUE TITLE
Chrome 50 canvas missing elements

### ISSUE THREAD

**Issue by Eolus** [niklasvh/html2canvas#871] opened 2016-05-08 22:11 UTC
I have an app that has successfully been using html2canvas for some time on Chrome, and which recently broke with the release of Chrome 50, but only on certain machines!  A few very simple DOM objects from the source HTML appear in the returned canvas, but most of the source HTML is not rendered to the canvas at all.  Only the very fastest machines exhibit the problem, however, and some machines with identical OS/browser versions work and some don't work.

After a day of gnashing my teeth over this problem, I discovered that turning OFF hardware acceleration under Chrome 50 Advanced Settings provides a complete work-around to the problem, and the original app now works unmodified on all machines.  I hope this will help someone else avoid the amount of time I wasted on this problem.

**Comment by programmin1** [comment] 2016-05-10 03:47
I would highly recommend reporting the bug here: https://bugs.chromium.org/p/chromium/issues/list
Hopefully they will fix the issue. Chrome can be especially buggy at times, like back when no-one on AMD processors could do JS profiling (https://bugs.chromium.org/p/chromium/issues/detail?id=469236) or last version where numerous sites had messed up jarring when scrolling because smooth-scrolling was turned on by default (https://bugs.chromium.org/p/chromium/issues/detail?id=599782)

Hopefully the next version is better - always good to keep testing on Chrome Beta.

**Comment by lgellert** [comment] 2016-05-19 20:16
I noticed the same issue in Chrome 50. As @Eolus mentioned, turning off hardware acceleration under advanced settings fixes it (thank you for that). However, that option is default checked in Chrome 50.

I spent some time digging in the code and setting breakpoints. I've confirmed the issue is happening in 0.4.1 and 0.5.0-beta3.  In 0.5.0-beta3, if I set a breakpoint in NodeParser.prototype.paint and step through slowly it renders correctly most of the time.  I tried setting the option {async: true}, and fiddling with the async delay but that didn't help.  

In my case, any element with a border-radius property wasn't rendering to the canvas, so removing that may be a temporary work around.

There are 277 open Chrome bugs that match 'hardware acceleration', many apply to Chrome 50+, hopefully one of these overlaps with this issue. https://bugs.chromium.org/p/chromium/issues/detail?id=611310&q=hardware%20acceleration&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Closed** 2017-07-27 06:25 UTC
