### ISSUE TITLE
Error: Cannot read property

### ISSUE THREAD

**Issue by thrownew** [niklasvh/html2canvas#529] opened 2015-02-06 17:08 UTC
In v0.5.0-alpha2 i catch strange error:

TypeError: Cannot read property '1' of null
    at GradientContainer.<anonymous> (html2canvas.js:2470:44)
    at Array.map (native)
    at GradientContainer.LinearGradientContainer (html2canvas.js:2467:66)
    at ImageLoader.13.ImageLoader.loadImage (html2canvas.js:2341:16)
    at ImageLoader.<anonymous> (html2canvas.js:2313:46)
    at Array.forEach (native)
    at ImageLoader.13.ImageLoader.addImage (html2canvas.js:2311:23)
    at Array.forEach (native)
    at ImageLoader.13.ImageLoader.findBackgroundImage (html2canvas.js:2305:71)
    at 29.exports.bind (html2canvas.js:4331:25)

**Comment by usmonster** [comment] 2015-02-06 17:44
Duplicate of #469. Please follow that one and feel free to close this one.

**Closed** 2015-02-06 20:20 UTC
