### ISSUE TITLE
Text gradient screenshot

### ISSUE THREAD

**Issue by zhaoxuan1701** [niklasvh/html2canvas#1831] opened 2019-05-10 08:40 UTC
There is a problem with the text gradient screenshot. Can you help me with it?
E.g
![{BE9E8B8C-3859-4E3A-8E1F-D92A1CC6C5AC}_20190510163640](https://user-images.githubusercontent.com/28032762/57514028-265a5200-7342-11e9-8eba-60e789f572dd.jpg)
after:
![7EBD3C82-037F-4917-9371-7DEA0788B94F](https://user-images.githubusercontent.com/28032762/57514118-4db11f00-7342-11e9-9924-c94edec4ff47.png)

**Comment by niklasvh** [comment] 2019-05-12 04:56
duplicate of https://github.com/niklasvh/html2canvas/issues/1208

**Closed by niklasvh** 2019-05-12 04:56 UTC
