### ISSUE TITLE
Not hiding overflowed content

### ISSUE THREAD

**Issue by elisoncampos** [niklasvh/html2canvas#560] opened 2015-03-25 21:16 UTC
I'm having trouble hiding overflowed content, the captured image show the content from the top, not from the position the user was scrolling.

In Browser:
![captura de tela 2015-03-25 as 18 10 05](https://cloud.githubusercontent.com/assets/5031917/6835649/e703ae42-d31a-11e4-8c09-adfb0bb2b7cc.png)

Generated Image
![captura de tela 2015-03-25 as 18 14 43](https://cloud.githubusercontent.com/assets/5031917/6835652/f157c144-d31a-11e4-8384-ff4a4684f1a8.png)

Any ideas how I can solve this issue?

**Comment by usmonster** [comment] 2015-03-26 12:35
Duplicate of #511. Feel free to follow that one and close this one (also make sure you're using the most recent version from the master branch, there was a partial fix a couple weeks ago).

**Closed** 2017-12-12 08:42 UTC
